//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizerFiles {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class Idioma : global::System.Configuration.ApplicationSettingsBase {
		
		private static Idioma defaultInstance = ((Idioma)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Idioma())));
		
		public static Idioma Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string AbrirCarpeta {
			get {
				return ((string)(this["AbrirCarpeta"]));
			}
			set {
				this["AbrirCarpeta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ArchivosHallados {
			get {
				return ((string)(this["ArchivosHallados"]));
			}
			set {
				this["ArchivosHallados"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string CantidadTotal {
			get {
				return ((string)(this["CantidadTotal"]));
			}
			set {
				this["CantidadTotal"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string CarpetaCreadaPara {
			get {
				return ((string)(this["CarpetaCreadaPara"]));
			}
			set {
				this["CarpetaCreadaPara"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string CarpetaPesa {
			get {
				return ((string)(this["CarpetaPesa"]));
			}
			set {
				this["CarpetaPesa"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string DesactiveExaminar {
			get {
				return ((string)(this["DesactiveExaminar"]));
			}
			set {
				this["DesactiveExaminar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Open folder")]
		public string EnAbrirCarpeta {
			get {
				return ((string)(this["EnAbrirCarpeta"]));
			}
			set {
				this["EnAbrirCarpeta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Name of the files found: ")]
		public string EnArchivosHallados {
			get {
				return ((string)(this["EnArchivosHallados"]));
			}
			set {
				this["EnArchivosHallados"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Total number of all files: ")]
		public string EnCantidadTotal {
			get {
				return ((string)(this["EnCantidadTotal"]));
			}
			set {
				this["EnCantidadTotal"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Folder created for ")]
		public string EnCarpetaCreadaPara {
			get {
				return ((string)(this["EnCarpetaCreadaPara"]));
			}
			set {
				this["EnCarpetaCreadaPara"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("The folder weighs: ")]
		public string EnCarpetaPesa {
			get {
				return ((string)(this["EnCarpetaPesa"]));
			}
			set {
				this["EnCarpetaPesa"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string EnCarpetarConExtension {
			get {
				return ((string)(this["EnCarpetarConExtension"]));
			}
			set {
				this["EnCarpetarConExtension"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string EncarpetarSinExtension {
			get {
				return ((string)(this["EncarpetarSinExtension"]));
			}
			set {
				this["EncarpetarSinExtension"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"Uncheck the Browse for Folders and Subfolders box to be able to use the Folder By Length setting. It is not possible to do this action if this box is activated, because this would cause all the files depending on their extension to be moved from their place of origin. It is not possible to do this action.")]
		public string EnDesactiveExaminar {
			get {
				return ((string)(this["EnDesactiveExaminar"]));
			}
			set {
				this["EnDesactiveExaminar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Archive based on file extension.")]
		public string EnEncarpetarConExtension {
			get {
				return ((string)(this["EnEncarpetarConExtension"]));
			}
			set {
				this["EnEncarpetarConExtension"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Archive regardless of file extension.")]
		public string EnEnCarpetarSinExtension {
			get {
				return ((string)(this["EnEnCarpetarSinExtension"]));
			}
			set {
				this["EnEnCarpetarSinExtension"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Write the route here or click on the magnifying glass.")]
		public string EnEscribeLaRuta {
			get {
				return ((string)(this["EnEscribeLaRuta"]));
			}
			set {
				this["EnEscribeLaRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Browse all folders (This action takes a while).")]
		public string EnExaminarCarpetas {
			get {
				return ((string)(this["EnExaminarCarpetas"]));
			}
			set {
				this["EnExaminarCarpetas"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("There was a problem, possible errors: • File path not found, or misspelled. • Acc" +
			"ess denied to the specified path. • Some effective file. A problem has occurred." +
			"")]
		public string EnHaOcurrido {
			get {
				return ((string)(this["EnHaOcurrido"]));
			}
			set {
				this["EnHaOcurrido"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Clean console")]
		public string EnLimpiar {
			get {
				return ((string)(this["EnLimpiar"]));
			}
			set {
				this["EnLimpiar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Do not file")]
		public string EnNoEncarpetar {
			get {
				return ((string)(this["EnNoEncarpetar"]));
			}
			set {
				this["EnNoEncarpetar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Organize")]
		public string EnOrganizar {
			get {
				return ((string)(this["EnOrganizar"]));
			}
			set {
				this["EnOrganizar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("There is no path to open the folder")]
		public string EnSinRuta {
			get {
				return ((string)(this["EnSinRuta"]));
			}
			set {
				this["EnSinRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("File types:")]
		public string EnTiposDeArchivos {
			get {
				return ((string)(this["EnTiposDeArchivos"]));
			}
			set {
				this["EnTiposDeArchivos"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string EscribeLaRuta {
			get {
				return ((string)(this["EscribeLaRuta"]));
			}
			set {
				this["EscribeLaRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ExaminarCarpetas {
			get {
				return ((string)(this["ExaminarCarpetas"]));
			}
			set {
				this["ExaminarCarpetas"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string HaOcurrido {
			get {
				return ((string)(this["HaOcurrido"]));
			}
			set {
				this["HaOcurrido"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Limpiar {
			get {
				return ((string)(this["Limpiar"]));
			}
			set {
				this["Limpiar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string NoEncarpetar {
			get {
				return ((string)(this["NoEncarpetar"]));
			}
			set {
				this["NoEncarpetar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Organizar {
			get {
				return ((string)(this["Organizar"]));
			}
			set {
				this["Organizar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string SinRuta {
			get {
				return ((string)(this["SinRuta"]));
			}
			set {
				this["SinRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Abrir carpeta")]
		public string SpAbrirCarpeta {
			get {
				return ((string)(this["SpAbrirCarpeta"]));
			}
			set {
				this["SpAbrirCarpeta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Archivar sin importar extensión del archivo.")]
		public string SpArchivarSinE {
			get {
				return ((string)(this["SpArchivarSinE"]));
			}
			set {
				this["SpArchivarSinE"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Nombre de los archivos hallados: ")]
		public string SpArchivosHallados {
			get {
				return ((string)(this["SpArchivosHallados"]));
			}
			set {
				this["SpArchivosHallados"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Cantidad total de todos los archivos: ")]
		public string SpCantidadTotal {
			get {
				return ((string)(this["SpCantidadTotal"]));
			}
			set {
				this["SpCantidadTotal"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Carpeta creada para ")]
		public string SpCarpetaCreadaPara {
			get {
				return ((string)(this["SpCarpetaCreadaPara"]));
			}
			set {
				this["SpCarpetaCreadaPara"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("La Carpeta pesa: ")]
		public string SpCarpetaPesa {
			get {
				return ((string)(this["SpCarpetaPesa"]));
			}
			set {
				this["SpCarpetaPesa"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"Desactive la casilla de Examinar Carpetas y Subcarpetas, para poder utilizar el parámetro de Encarpetar Según su Extención. No es posible hacer esta acción si esa casilla está activa, porque esto haría que todos los archivos dependiendo de su extensión sean movidos de su lugar de origen. No es posible hacer esta acción.")]
		public string SpDesactiveExaminar {
			get {
				return ((string)(this["SpDesactiveExaminar"]));
			}
			set {
				this["SpDesactiveExaminar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("English")]
		public string SpEn {
			get {
				return ((string)(this["SpEn"]));
			}
			set {
				this["SpEn"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Archivar según la extensión del archivo.    ")]
		public string SpEncarpetarConExtension {
			get {
				return ((string)(this["SpEncarpetarConExtension"]));
			}
			set {
				this["SpEncarpetarConExtension"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Escribe la ruta aquí o click en la lupa.")]
		public string SpEscribeLaRuta {
			get {
				return ((string)(this["SpEscribeLaRuta"]));
			}
			set {
				this["SpEscribeLaRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Examinar todas las carpetas (Esta acción tarda un poco).")]
		public string SpExaminarCarpetas {
			get {
				return ((string)(this["SpExaminarCarpetas"]));
			}
			set {
				this["SpExaminarCarpetas"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Hubo un problema, posibles errores:• Ruta de los archivos no encontrada, o mal es" +
			"crita.• Acceso denegado a la ruta especificada.• Algún archivo efectuoso.Ha ocur" +
			"rido un problema.")]
		public string SpHaOcurrido {
			get {
				return ((string)(this["SpHaOcurrido"]));
			}
			set {
				this["SpHaOcurrido"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Limpiar consola")]
		public string SpLimpiar {
			get {
				return ((string)(this["SpLimpiar"]));
			}
			set {
				this["SpLimpiar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("No archivar")]
		public string SpNoEncarpetar {
			get {
				return ((string)(this["SpNoEncarpetar"]));
			}
			set {
				this["SpNoEncarpetar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Organizar")]
		public string SpOrganizar {
			get {
				return ((string)(this["SpOrganizar"]));
			}
			set {
				this["SpOrganizar"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("No hay una ruta para abrir la carpeta")]
		public string SpSinRuta {
			get {
				return ((string)(this["SpSinRuta"]));
			}
			set {
				this["SpSinRuta"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Tipos de archivos:")]
		public string SpTiposDeArchivos {
			get {
				return ((string)(this["SpTiposDeArchivos"]));
			}
			set {
				this["SpTiposDeArchivos"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string TiposDeArchivos {
			get {
				return ((string)(this["TiposDeArchivos"]));
			}
			set {
				this["TiposDeArchivos"] = value;
			}
		}
	}
}
